# .github/workflows/mirror-to-personal.yml
name: Mirror to Adam Personal Repo

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to personal repo
        env:
          TOKEN: ${{ secrets.ADAM_GH_PAT }}
        if: github.repository == 'PinewoodRobotics/pinewood-one'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Clone the org repo manually (DON'T use actions/checkout)
          git clone https://github.com/PinewoodRobotics/pinewood-one.git source
          cd source

          # Add your personal repo as a new remote
          git remote add personal https://x-access-token:${TOKEN}@github.com/AdamEXu/pinewood-one.git

          # Push just main branch (or --mirror if you prefer)
          git push personal main --force
